export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_FAILURE = 'GET_CHARACTERS_FAILURE';

export const GET_CHARACTERS_DATA = 'GET_CHARACTERS_DATA';
export const GET_CHARACTERS_DATA_SUCCESS = 'GET_CHARACTERS_DATA_SUCCESS';
export const GET_CHARACTERS_DATA_FAILURE = 'GET_CHARACTERS_DATA_FAILURE';

export const ADD_CHARACTER = 'ADD_CHARACTER';
export const ADD_CHARACTER_SUCCESS = 'ADD_CHARACTER_SUCCESS';
